# Generated by Django 5.1.7 on 2025-04-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reward_type',
            field=models.CharField(choices=[('cash', 'Cash Reward'), ('discount', 'Discount Amount'), ('points', 'Reward Points'), ('gift', 'Gift Card')], default='cash', max_length=20),
        ),
    ]
